// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1646918365);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1646918338);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1653481254);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1646918395);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 382);
user_pref("browser.cache.disk.capacity", 819200);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1646918335);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.migration.version", 96);
user_pref("browser.newtabpage.activity-stream.impressionId", "{a8a53114-ad3d-4380-a808-3fa6f3607e52}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20200720193547");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1653481252");
user_pref("browser.slowStartup.averageTime", 2988);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20200720193547");
user_pref("browser.startup.homepage_override.mstone", "79.0");
user_pref("browser.startup.lastColdStartupCheck", 1653481252);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1646918337459");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "79.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "1007a1de5915447ea8188ff7fd1d376a");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20200720193547");
user_pref("extensions.lastAppVersion", "79.0");
user_pref("extensions.lastPlatformVersion", "79.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"aa35e21f-0091-4501-bdb5-fcfd8c80757c\",\"formautofill@mozilla.org\":\"627dcd7e-bd2f-4430-b3a7-62e06fc35917\",\"screenshots@mozilla.org\":\"4027088e-c158-4133-bfc6-3547f9f8728a\",\"webcompat-reporter@mozilla.org\":\"4543ad92-b343-454f-9ac2-5177eca593be\",\"webcompat@mozilla.org\":\"b3d1a997-5143-49f8-ac48-ed61adf44c70\",\"default-theme@mozilla.org\":\"23c6687c-6cff-4b50-8f96-91febb48f8cd\",\"google@search.mozilla.org\":\"9787d675-2060-4a4b-838e-d2676928d7f9\",\"amazondotcom@search.mozilla.org\":\"f322c411-6343-41c9-b711-4e4d4b1a0192\",\"wikipedia@search.mozilla.org\":\"a4a36c3a-053c-4826-b767-c51622da76ed\",\"bing@search.mozilla.org\":\"cc3dde3e-7e66-43ec-9568-c0039fdb993b\",\"ddg@search.mozilla.org\":\"c285adcf-e5ea-4a66-80f6-05fd29b0fc89\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("media.gmp-manager.buildID", "20200720193547");
user_pref("media.gmp-manager.lastCheck", 1646918416);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.remote_settings.intermediates.checked", 1646889634);
user_pref("security.sandbox.content.tempDirSuffix", "5f171c3a-45c2-45da-9d3b-78761132c28b");
user_pref("security.sandbox.plugin.tempDirSuffix", "57ba0884-44f8-4734-80a6-7a2576588124");
user_pref("services.blocklist.gfx.checked", 1646889634);
user_pref("services.settings.clock_skew_seconds", 28796);
user_pref("services.settings.last_update_seconds", 1646889634);
user_pref("services.settings.main.cfr.last_check", 1646889634);
user_pref("services.settings.main.message-groups.last_check", 1646889634);
user_pref("services.settings.main.normandy-recipes-capabilities.last_check", 1646889634);
user_pref("toolkit.startup.last_success", 1653481249);
user_pref("toolkit.telemetry.cachedClientID", "a05e9a10-7024-443a-9caa-d573506c9693");
user_pref("toolkit.telemetry.previousBuildID", "20200720193547");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
